// ====================================
// AI PROCUREMENT PAGE
// ====================================
//
// Future ML.NET procurement intelligence.
//
// Current responsibilities:
// - Explain the planned capability
// - Provide a truthful feature state
// - Avoid presenting fabricated predictions
//
// The actual intelligence engine will later
// be connected through the business layer:
//
// Page
//   ↓
// Business Hook
//   ↓
// Repository
//   ↓
// Service
//   ↓
// ML.NET / Backend
// ====================================

import React from "react";

import {
    BrainCircuit,
    Sparkles,
    BarChart3,
    ShoppingCart
} from "lucide-react";

import {
    Card,
    EmptyState
} from "../components/ui";

import {
    useTheme
} from "../context/ThemeContext";

// ====================================
// COMPONENT
// ====================================

const AIProcurement = () => {

    const {
        theme,
        isDark
    } = useTheme();

    return (

        <div
            style={{
                display: "flex",
                flexDirection: "column",
                gap: theme.spacing.lg
            }}
        >

            {/* ==================================
                PAGE HEADER
                ================================== */}

            <div>

                <div
                    style={{
                        display: "flex",
                        alignItems: "center",
                        gap: theme.spacing.sm
                    }}
                >

                    <div
                        style={{
                            width: "42px",
                            height: "42px",
                            display: "flex",
                            alignItems: "center",
                            justifyContent: "center",
                            borderRadius:
                                theme.radius.md,
                            backgroundColor:
                                isDark
                                    ? "rgba(255,255,255,0.05)"
                                    : "rgba(52,114,156,0.08)",
                            color:
                                theme.colors.primary
                        }}
                    >
                        <BrainCircuit size={21} />
                    </div>

                    <div>

                        <h1
                            style={{
                                margin: 0,
                                fontSize:
                                    theme.typography
                                        .fontSize.xxl,
                                fontWeight:
                                    theme.typography
                                        .fontWeight
                                        .extrabold,
                                color:
                                    theme.colors.text,
                                letterSpacing:
                                    theme.typography
                                        .letterSpacing
                                        .tight
                            }}
                        >
                            AI Procurement Intelligence
                        </h1>

                        <p
                            style={{
                                margin:
                                    `${theme.spacing.xxs} 0 0`,
                                color:
                                    theme.colors.textMuted,
                                fontSize:
                                    theme.typography
                                        .fontSize.sm
                            }}
                        >
                            Future machine-learning support for
                            predictive procurement and inventory
                            decision-making.
                        </p>

                    </div>

                </div>

            </div>

            {/* ==================================
                FEATURE STATUS
                ================================== */}

            <Card
                variant="glass"
                isDark={isDark}
                padding="lg"
            >

                <EmptyState
                    icon={BrainCircuit}
                    isDark={isDark}
                    title="Procurement intelligence is not connected yet"
                    description={
                        "The procurement intelligence engine is planned as the final ML.NET feature. No predictive recommendations, savings estimates, confidence scores, or automatic purchase orders are generated by the current system."
                    }
                />

            </Card>

            {/* ==================================
                PLANNED CAPABILITIES
                ================================== */}

            <Card
                variant="glass"
                isDark={isDark}
                padding="lg"
            >

                <div
                    style={{
                        display: "flex",
                        alignItems: "center",
                        gap: theme.spacing.sm,
                        marginBottom:
                            theme.spacing.lg
                    }}
                >

                    <Sparkles
                        size={18}
                        color={
                            theme.colors.primary
                        }
                    />

                    <div>

                        <h2
                            style={{
                                margin: 0,
                                fontSize:
                                    theme.typography
                                        .fontSize.md,
                                fontWeight:
                                    theme.typography
                                        .fontWeight
                                        .bold,
                                color:
                                    theme.colors.text
                            }}
                        >
                            Planned intelligence capabilities
                        </h2>

                        <p
                            style={{
                                margin:
                                    `${theme.spacing.xxs} 0 0`,
                                fontSize:
                                    theme.typography
                                        .fontSize.xs,
                                color:
                                    theme.colors.textMuted
                            }}
                        >
                            These are planned capabilities, not
                            currently generated system outputs.
                        </p>

                    </div>

                </div>

                <div
                    style={{
                        display: "grid",
                        gridTemplateColumns:
                            "repeat(auto-fit, minmax(220px, 1fr))",
                        gap: theme.spacing.md
                    }}
                >

                    <CapabilityCard
                        theme={theme}
                        isDark={isDark}
                        icon={BarChart3}
                        title="Demand prediction"
                        description={
                            "Use historical sales and inventory data to estimate future demand."
                        }
                    />

                    <CapabilityCard
                        theme={theme}
                        isDark={isDark}
                        icon={ShoppingCart}
                        title="Restock recommendations"
                        description={
                            "Translate predicted demand into suggested replenishment quantities."
                        }
                    />

                    <CapabilityCard
                        theme={theme}
                        isDark={isDark}
                        icon={BrainCircuit}
                        title="Procurement intelligence"
                        description={
                            "Combine inventory, sales, and supplier information to support procurement decisions."
                        }
                    />

                </div>

            </Card>

        </div>
    );
};

// ====================================
// CAPABILITY CARD
// ====================================

const CapabilityCard = ({
    theme,
    isDark,
    icon: Icon,
    title,
    description
}) => {

    return (

        <div
            style={{
                padding: theme.spacing.md,
                border:
                    `1px solid ${theme.colors.border}`,
                borderRadius:
                    theme.radius.lg,
                backgroundColor:
                    isDark
                        ? "rgba(255,255,255,0.03)"
                        : "rgba(52,114,156,0.03)"
            }}
        >

            <div
                style={{
                    width: "36px",
                    height: "36px",
                    display: "flex",
                    alignItems: "center",
                    justifyContent: "center",
                    borderRadius:
                        theme.radius.md,
                    backgroundColor:
                        isDark
                            ? "rgba(255,255,255,0.05)"
                            : "rgba(52,114,156,0.08)",
                    color:
                        theme.colors.primary,
                    marginBottom:
                        theme.spacing.sm
                }}
            >
                <Icon size={18} />
            </div>

            <h3
                style={{
                    margin:
                        `0 0 ${theme.spacing.xs}`,
                    color:
                        theme.colors.text,
                    fontSize:
                        theme.typography
                            .fontSize.sm,
                    fontWeight:
                        theme.typography
                            .fontWeight
                            .bold
                }}
            >
                {title}
            </h3>

            <p
                style={{
                    margin: 0,
                    color:
                        theme.colors.textMuted,
                    fontSize:
                        theme.typography
                            .fontSize.xs,
                    lineHeight:
                        theme.typography
                            .lineHeight
                            .normal
                }}
            >
                {description}
            </p>

        </div>
    );
};

export default AIProcurement;